<a href="https://colab.research.google.com/github/vishu0047/Paper_code/blob/master/BERt_vs_DistillBERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install transformer


  ERROR: Could not find a version that satisfies the requirement transformer (from versions: none)
ERROR: No matching distribution found for transformer


In [6]:
pip install tensorflow==2.0.0-rc0

     |████████████████████████████████| 86.3MB 1.2MB/s 
     |████████████████████████████████| 4.3MB 40.0MB/s 
     |████████████████████████████████| 501kB 45.8MB/s 
  Found existing installation: tensorflow 1.14.0
    Uninstalling tensorflow-1.14.0:
      Successfully uninstalled tensorflow-1.14.0


In [8]:
pip install transformers

     |████████████████████████████████| 296kB 4.8MB/s 
     |████████████████████████████████| 1.0MB 37.7MB/s 
     |████████████████████████████████| 655kB 41.4MB/s 
     |████████████████████████████████| 860kB 44.3MB/s 
  Created wheel for regex: filename=regex-2019.8.19-cp36-cp36m-linux_x86_64.whl size=609239 sha256=af5fc2dc1179b42034188a103a343c91e9f6640ebfdc6125a1ac5cd5cc6892b9
  Stored in directory: /root/.cache/pip/wheels/90/04/07/b5010fb816721eb3d6dd64ed5cc8111ca23f97fdab8619b5be
  Created wheel for sacremoses: filename=sacremoses-0.0.34-cp36-none-any.whl size=883992 sha256=e77a42b865f9e729b2eaf6e9b3036a7cc1dde44a040d72d09d6ca5528d529485
  Stored in directory: /root/.cache/pip/wheels/07/b9/5b/8bd674c23e962fbff34420a9fa7a2c374d591ecadd5bc37684
Successfully built regex sacremoses


In [0]:
import numpy
import tensorflow as tf
from transformers import *

In [11]:
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

100%|██████████| 231508/231508 [00:00<00:00, 1240018.30B/s]


In [20]:
model = TFDistilBertModel.from_pretrained('distilbert-base-uncased')

100%|██████████| 363423424/363423424 [00:10<00:00, 36061744.07B/s]


In [0]:
text = "[CLS] Who was Jim Henson ? Jim [MASK] was a puppeteer [SEP]"
tokens = tokenizer.encode(text)

In [22]:
print(tokens)

[101, 2040, 2001, 3958, 27227, 1029, 3958, 103, 2001, 1037, 13997, 11510, 102]


In [0]:
tf_inputs = tf.constant([tokens])

In [24]:
print(tf_inputs)

tf.Tensor(
[[  101  2040  2001  3958 27227  1029  3958   103  2001  1037 13997 11510
    102]], shape=(1, 13), dtype=int32)


In [0]:
tf_output = model(tf_inputs,training=False)

In [27]:
print(tf_output)

(<tf.Tensor: id=4085, shape=(1, 13, 768), dtype=float32, numpy=
array([[[-0.21021019,  0.13284668,  0.00259679, ..., -0.0115498 ,
          0.28256565,  0.3349731 ],
        [-0.6021809 ,  0.00682241,  0.05841997, ...,  0.01242756,
          0.3346558 , -0.41981506],
        [-0.55397725, -0.05069625, -0.24984339, ...,  0.08756064,
          0.37719464,  0.20139967],
        ...,
        [-0.01019667, -0.22512233,  0.19934413, ...,  0.03522625,
          0.45433873,  0.5077871 ],
        [-0.21602084,  0.17490914,  0.2615769 , ...,  0.19644357,
          0.1490563 , -0.19996664],
        [ 0.8434901 ,  0.46343035, -0.23264432, ...,  0.2449837 ,
         -0.26064926, -0.0995862 ]]], dtype=float32)>,)


In [28]:
tokenizer1 = BertTokenizer.from_pretrained('bert-base-uncased')
model_bert = TFBertModel.from_pretrained('bert-base-uncased')

100%|██████████| 536063208/536063208 [00:15<00:00, 33688777.56B/s]


In [0]:
tex_1 = "[CLS] Who was Jim Henson ? Jim [MASK] was a puppeteer [SEP]"
token_1 = tokenizer1.encode(text1)

In [0]:
tf_input_1 = tf.constant([token_1])

In [0]:
tf_output_1= model_bert(tf_input_1, training=False)

In [34]:
print(tf_output_1)

(<tf.Tensor: id=12623, shape=(1, 13, 768), dtype=float32, numpy=
array([[[-0.08862583,  0.12331912, -0.04344402, ..., -0.15937367,
          0.3462374 ,  0.29925236],
        [-1.0924177 ,  0.30834728, -0.05347633, ..., -0.03328572,
          0.0647072 , -0.29891902],
        [ 0.09913804, -0.5699878 , -0.32382083, ..., -0.11139255,
          0.40436238,  0.52995265],
        ...,
        [ 0.21172668,  0.07650962,  0.23238865, ...,  0.11162611,
          0.8309876 ,  0.35223114],
        [-0.25335768, -0.04377572,  0.26526996, ...,  0.5064801 ,
          0.13923964, -0.16921747],
        [ 0.7615249 ,  0.3997792 , -0.16638292, ...,  0.3211632 ,
         -0.33306694, -0.0228935 ]]], dtype=float32)>, <tf.Tensor: id=12632, shape=(1, 768), dtype=float32, numpy=
array([[-7.45368958e-01, -2.41569102e-01,  6.17856026e-01,
         3.26964408e-01, -3.16819340e-01, -1.81646973e-01,
         7.66066015e-01,  1.58885419e-01,  5.20892084e-01,
        -9.99109387e-01,  1.03382923e-01, -1.06921464e

In [0]:
import scipy
sim = 1-scipy.spatial.distance.cosine(tokens,token_1)

In [37]:
print(sim)

1.0
